### ISSUE TITLE
Normalizing path in Express

### ISSUE THREAD

**Issue by analytik** [roylines/node-epimetheus#10]
Hi,

First of all, thanks for this neat library! It helped me get a kick start with exporting metrics to Prometheus.

However, in our projects, we often use parameters in Express routes, and these paths don't get normalized right now, so for example if you have a route like `/user/:userId` and then people make requests to `/user/milan` and `/user/milan123`, this creates new labels in Prometheus, which I gather is an antipattern - it works well only for a limited number of labels.

I'm currently working around it by not reporting path at all, and putting hostname there instead, as we run a bunch of microservices, so that's more useful for us. Not sure if this is a very common use case.

Any thoughts? I don't expect you to solve our problems of course :D Was just wondering if you encountered this; I'll hopefully prioritize this and work on getting it fixed in the next few days or weeks.

**Comment by roylines** [comment]
Hi!

I see the issue. 

The module currently uses request.path to determine the label to apply. I will need to investigate if there is a way to get a parameterless url for the path through express. If you find a way, please let me know. Before I can implement, I will need to find an equivalent for the other supported methods too - in particular hapi and restify. 

I'll take a look at the weekend.

Roy.

**Comment by roylines** [comment]
OK - had a thought about this. For strict REST a full (not ending in /) URL names a resource, while one ending in a slash '/' is a list of resources. 

I will take the strict approach and only label up to the last trailing /

The following examples demonstrate the approach:

- **/resource/10** will label as **/resource/**
- **/resource/** will label as **/resource/**

I will add an additional label of **cardinality** that can have the values: **one** or **many** to allow distinguishing between, for example, requesting all users with /users/ or a single user with /users/freddie

**Comment by roylines** [comment]
@analytik fix made to epimetheus@1.0.38. Please give it a try and let me know if it improves your situation. I've basically assumed, as per strict spec, that urls not ending in a / are resources and trim back to the /.

e.g. /users/freddie now has label of /users/
in order to distinguish /users/ from /users/freddie I've added another label cardinality that will have the value 'one' for /users/freddie and 'many' for /users/ to enable the urls to be distinguished.

**Comment by analytik** [comment]
Thanks! This seems to work well for some of our services, but one frontend library loads some of the URLs with an ending slash, like `/stuff/foobar/` even when Express defines it as `'/stuff/:param'`. This is probably a rare use case and not the best practice, so your solution probably works well for most people.

I'll investigate if there's an easy way to access Express routes, I don't know much about its internals, but I'll report here if/when I find a usable solution.

**Comment by analytik** [comment]
Turned out that we had some more complex routes like `/stuff/:param1/:param2`, but luckily the only change it needed was changing `request.path` to `request.route.path` in express.js.
