### ISSUE TITLE
Enable route based path logging for Express

### ISSUE THREAD

**Issue by voxpelli** [roylines/node-epimetheus#16]
Rather than the path splitting that's going on with [`req.path`](http://expressjs.com/en/4x/api.html#req.path) in the [current Express implementation](https://github.com/roylines/node-epimetheus/blob/17c1e7d0f232bcb01788df5eaa377302d3da9a41/lib/express.js#L7) I would prefer to instead base the logging on [`req.route`](http://expressjs.com/en/4x/api.html#req.route).

That would group the metrics better for me, by grouping it on eg. `/user/:username`, which would be easier to map to the logic in my Express app.

**Comment by voxpelli** [comment]
Just a note – to get the full path, one needs to do: `req.baseUrl + req.route.path`

**Comment by roylines** [comment]
Please provide a pull request
