### ISSUE TITLE
node_* metrics

### ISSUE THREAD

**Issue by errordeveloper** [roylines/node-epimetheus#29]
As `prometheus-gc-stats` as well as `prom-client` use `nodejs_*`, and node exporter owns the `node_*` namespace, it's probably a good idea to rename `node_*` to `nodejs_*`.

**Comment by errordeveloper** [comment]
Let's figure how this could introduce, perhaps a major version bump would be sufficient?

**Comment by errordeveloper** [comment]
In fact, it looks like all of `node_*` metrics have equivalents provided by `prom-client`, e.g. `process_resident_memory_bytes` and `node_memory_rss_bytes`,  `process_heap_bytes` and `node_memory_heap_used_bytes`... some of these appear different in my test, so let's figure it out.

**Comment by errordeveloper** [comment]
@tcolgate @Olical removed `node_*` metrics in their fork.

**Comment by roylines** [comment]
Happy to take a pull request on this. Please follow these [guidelines](http://blog.ploeh.dk/2015/01/15/10-tips-for-better-pull-requests/) if you do
