### ISSUE TITLE
prom-client version

### ISSUE THREAD

**Issue by errordeveloper** [roylines/node-epimetheus#30]
It appears that this library is incompatible with latest version of `prom-client` (well, it's documented only in `package.json` and there is no explanation in the commit that sets it to `< 7` ( c2b74128bf960d41a95fd80c8b76fd8053c7d46c). Let's determine what is the issue with latest `prom-client` (v9.1.0) and see how it can be fixed.

**Comment by diasdavid** [comment]
Hi @errordeveloper, I've just PR'ed a big update to all the deps on https://github.com/roylines/node-epimetheus/pull/32 and @roylines did the favor of reviewing, merging and publishing super fast 🚀

You shouldn't have any more issues now :)
